# Generated by Django 6.0.2 on 2026-02-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('total_plays', models.IntegerField(default=0)),
                ('unique_tracks', models.IntegerField(default=0)),
                ('unique_artists', models.IntegerField(default=0)),
                ('top_tracks', models.JSONField(default=list)),
                ('top_artists', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resonate_app.spotifyuser')),
            ],
            options={
                'unique_together': {('spotify_user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=300)),
                ('artist_name', models.CharField(max_length=300)),
                ('artist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('album_name', models.CharField(blank=True, max_length=300, null=True)),
                ('album_image_url', models.URLField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('played_at', models.DateTimeField()),
                ('month', models.CharField(max_length=7)),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='resonate_app.spotifyuser')),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['spotify_user', 'month'], name='resonate_ap_spotify_ee6bd6_idx'), models.Index(fields=['spotify_user', 'year'], name='resonate_ap_spotify_e38774_idx'), models.Index(fields=['played_at'], name='resonate_ap_played__d29413_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('week', models.IntegerField()),
                ('total_plays', models.IntegerField(default=0)),
                ('unique_tracks', models.IntegerField(default=0)),
                ('unique_artists', models.IntegerField(default=0)),
                ('top_tracks', models.JSONField(default=list)),
                ('top_artists', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resonate_app.spotifyuser')),
            ],
            options={
                'unique_together': {('spotify_user', 'month', 'week')},
            },
        ),
    ]
